---
- name: Import PGP key
  become: True
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
    validate_certs: yes
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker repository
  become: True
  apt_repository:
    repo: "deb [arch=armhf] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
    mode: 0644
    validate_certs: yes

- name: Install Docker-CE
  become: True
  apt:
    name: '{{ item }}'
    state: latest
    autoclean: yes
    cache_valid_time: 86400
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
#TODO ignore error, reboot and try again

- name: Ensure pi user is in Docker group
  become: True
  user:
    name: pi
    groups: docker
    append: yes
#TODO add the following as a handler after the change
#- name: reset ssh connection
#  meta: reset_connection

- name: Ensure Docker dependensies are installed
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose

- name: Create a network with custom IPv4 IPAM config
  community.general.docker_network:
    name: backend
    ipam_config:
      - subnet: 172.20.0.0/16