---
- name: Import PGP key
  become: True
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present
    validate_certs: yes
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker repository
  become: True
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
    mode: 0644
    validate_certs: yes

- name: Install Docker-CE
  become: True
  apt:
    name: '{{ item }}'
    state: latest
    autoclean: yes
    cache_valid_time: 86400
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Ensure pi user is in Docker group
  become: True
  user:
    name: pi
    groups: docker
    append: yes